### ISSUE TITLE
Bug: Irresponsive Summing Receiver (Check Detector Status)

### ISSUE THREAD

**Issue by kferjaoui** [epoc-ed/GUI#50]
Concerning the "Summing Receiver Controls" in the Visualization panel (/feature/redis_config branch for now ), I happens that when in pedestal mode, the detector becomes idle (```g status``` -> status idle) and needs to be restarted using ```p start```. During that time, Receiver Controls are irresponsible (as expected) but detector behavior is odd...

Integration of the receiver controls with the GUI might be the cause but not yet sure how exactly...

**Comment by erikfrojdh** [comment]
Closing this since we migrated to jfj
